extends Node

enum FACTIONS {NONE, HUMAN, CREATURE, MONSTER}
enum ITEM_TYPES {ITEM, ARMOUR, WEAPON, CONSUMABLE}
enum ARMOUR_TYPES {HEAD, BODY, HANDS, FEET}
enum WEAPON_TYPES {SWORD, AXE, MACE, SPEAR, DAGGER, GREAT_SWORD, GREAT_AXE, FIRE, FROST, SHOCK, CHARACTER}
enum DAMAGE_TYPES {PHYSICAL, FIRE, FROST, POISON, SHOCK, EXPLOSION}
enum STAT_TYPES {
	HEALTH,
	HEALTH_MULT,
	SPEED,
	SPEED_MULT,
	DEFENCE,
	DEFENCE_MULT,
	CRIT_HIT_CHANCE,
	CRIT_HIT_MULT,
	ATTACK_SPEED_MULT,
}

var STATS = [
	"health",
	"health_mult",
	"speed",
	"speed_mult",
	"defence",
	"defence_mult",
	"crit_hit_chance",
	"crit_hit_mult",
	"attack_speed_mult",
]
